---
- hosts: localhost
  connection: local
  become: true
  pre_tasks:
    - name: update repository index (Ubuntu)
      tags: always
      apt:
        update_cache: yes
        upgrade: yes
      changed_when: false # This will never report 'changed' status
      when: ansible_distribution == "Ubuntu" # task will run only on Ubuntu
  roles:
    # - system
    # - setup-secure-remote-docker-daemon
      - docker-install