docker_machine_version: '0.16.2'
docker_compose_version: '1.26.2'
docker_packages:
  - docker-ce
  - docker-ce-cli 
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
pre_docker_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - software-properties-common
  - lsb-release