- name: "Ensure this role is running on Ubuntu/Debian"
  assert:
    that: ansible_os_family == "Debian"
    msg: "This role only works for Ubuntu/Debian !!"

- name: "Ensure required parameters are provided"
  assert: 
    that: "{{ item }} != \"\""
  with_items:
    - rootca_certificate
    - server_certificate
    - server_privatekey

- name: "Install Docker"
  include_role:
    name: docker-install

- name: "Install Certificates"
  include_tasks: install-certificates.yml # can also use import tasks (explicit way): /tasks/install-certificates.yml

- name: "Setup Docker daemon Service"
  include_tasks: setup-docker-service.yml
